# Generated by Django 5.1.3 on 2024-11-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_profile_email_alter_profile_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='shipping_email',
        ),
    ]
