# Generated by Django 5.1.3 on 2024-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shippingorder_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
