# Generated by Django 5.1.3 on 2024-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingorder_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='date_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
