# Generated by Django 5.1.3 on 2024-11-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_shippingorder_date_shipped'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
