# Generated by Django 5.1.3 on 2024-11-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
